### ISSUE TITLE
typo in IssueRequest.php - getFieldsForAction() calls 'getComments' rather than 'getFieldsForAction'

### ISSUE THREAD

**Issue by tmak7** [cpliakas/jira-client#18]
Hi,

In Jira/Request/IssueRequest.php there seems to be a typo where getFieldsForAction() calls 'getComments' rather than 'getFieldsForAction'.

**Comment by cpliakas** [comment]
Thanks for bringing this up. If a pull request can be created, I will definitely merge it. To be transparent, I am unlikely to apply this fix myself, so I am looking for some help.

**Comment by tmak7** [comment]
sure - created a pull request at https://github.com/cpliakas/jira-client/pull/19

**Comment by cpliakas** [comment]
Thanks!
